from generator.table_method_name import TableMethodName

class RedisTableWriter(object):
	def __init__(self, file_name, table_desc_array):
		self.file_name = file_name
		self.table_desc_array = table_desc_array
		self.table_method_name = TableMethodName()

	def write(self):
		with open(self.file_name, 'w') as f:
			self.write_class_head(f)
			self.write_class_body(f)
			f.flush()
	
	def write_class_head(self, f):
		f.write('#This file is generated by program. DO NOT EDIT IT MANUALLY!\n')
		f.write('class RedisTable(object):\n')
	
	def write_class_body(self, f):
		for table_desc in self.table_desc_array:
			table_type = table_desc['table_type']
			if table_type == 'map':
				self.write_map_table(table_desc, f)
			elif table_type == 'list':
				self.write_list_table(table_desc, f)
			elif table_type == 'list_map':
				self.write_list_map_table(table_desc, f)	
			elif table_type == 'global_list':
				self.write_global_list_table(table_desc, f)
			elif table_type == 'global_sorted_set':
				self.write_global_sorted_set_table(table_desc, f)
			elif table_type == 'sorted_set':
				self.write_sorted_set_table(table_desc, f)
				
	def write_map_table(self, table_desc, f):
		f.write('\tdef ' + self.table_method_name.get_table_method_name(table_desc['table_name']) + '(self, id_string):\n')
		f.write("\t\treturn '" + table_desc['table_name'] + ":' + id_string\n\n")
		
		for field in table_desc['table_field'].keys():
			f.write('\tdef ' + self.table_method_name.get_table_field_method_name(table_desc['table_name'], field) + '(self):\n')
			f.write("\t\treturn '" + field + "'\n\n")

	def write_list_table(self, table_desc, f):
		f.write('\tdef ' + self.table_method_name.get_list_method_name(table_desc['table_name']) + '(self, id_string):\n')
		f.write("\t\treturn '" + table_desc['table_name'] + "_list:' + id_string\n\n")
	def write_list_map_table(self, table_desc, f):
		self.write_list_table(table_desc, f)
		self.write_map_table(table_desc, f)
		
	def write_global_list_table(self, table_desc, f):
		f.write('\tdef ' + self.table_method_name.get_list_method_name(table_desc['table_name']) + '(self):\n')
		f.write("\t\treturn '" + table_desc['table_name'] + "_list'\n\n")
		
	def write_global_sorted_set_table(self, table_desc, f):
		f.write('\tdef ' + self.table_method_name.get_table_method_name(table_desc['table_name']) + '(self):\n')
		f.write("\t\treturn '" + table_desc['table_name'] + "'\n\n")
		
	def write_sorted_set_table(self, table_desc, f):
		f.write('\tdef ' + self.table_method_name.get_table_method_name(table_desc['table_name']) + '(self, id_string):\n')
		f.write("\t\treturn '" + table_desc['table_name'] + ":' + id_string\n\n")
"""
#This file is generated by program. DO NOT EDIT IT MANUALLY!
class RedisTable(object):
	def get_user_key(self, id):
		return 'user:' + id
	
	def get_user_table_user_id_field(self):
		return 'user_id'
	
	#list map table
	def get_friend_list_key(self, id):
		return 'friend_list:' + id 
	
	def get_friend_key(self, id):
		return 'friend:' + id
	
	def get_friend_table_user_id_field(self):
		return 'user_id'
		
	#list table
	def get_item_list_key(self, id):
		return 'item_list:' + id
	
	#global list table
	def get_online_player_list_key(self):
		return 'online_player_list'
	
	#global sorted set table
	def get_level_rank_key(self):
		return 'level_rank'
	
	#sorted set table
	def get_race_score_rank_key(self, id_string):
		return 'race_score_rank:' + id_string
"""