class PlainClassWriter(object):
	def __init__(self, path, table_desc):
		self.path = path
		self.table_desc = table_desc

	def write(self):
		with open(self.get_file_name(), 'w') as f:
			self.write_class_head(f)
			self.write_init_function(f)
			self.write_class_body(f)
			f.flush()
		
	def write_class_head(self, f):
		f.write('#This file is generated by program. DO NOT EDIT IT MANUALLY!\n')
		f.write('class ' + self.get_class_name() + '(object):\n')

	def write_init_function(self):
		pass
	
	def write_class_body(self, f):
		pass
	
	def get_file_name(self):
		return self.path + self.table_desc['table_name'] + '.py'
	
	def get_class_name(self):
		pass
	
