#This file is generated by program. DO NOT EDIT IT MANUALLY!
from redis_client.redis_table import RedisTable

class RedisAccessor(object):
	def __init__(self):
		self.redis_table = RedisTable()

	def get_user(self, redis, id_string):
		return redis.hgetall(self.redis_table.get_user_key(id_string))

	def get_user_table_user_name(self, redis, id_string):
		return redis.hget(
			self.redis_table.get_user_key(id_string),
			self.redis_table.get_user_table_user_name_field()
			)

	def get_user_table_user_id(self, redis, id_string):
		return redis.hget(
			self.redis_table.get_user_key(id_string),
			self.redis_table.get_user_table_user_id_field()
			)

	def get_item_list(self, redis, id_string):
		return redis.get(self.redis_table.get_item_list_key(id_string))

	def get_friend_list(self, redis, id_string):
		return redis.get(self.redis_table.get_friend_list_key(id_string))

	def get_friend(self, redis, id_string):
		return redis.hgetall(self.redis_table.get_friend_key(id_string))

	def get_friend_table_user_name(self, redis, id_string):
		return redis.hget(
			self.redis_table.get_friend_key(id_string),
			self.redis_table.get_friend_table_user_name_field()
			)

	def get_friend_table_user_id(self, redis, id_string):
		return redis.hget(
			self.redis_table.get_friend_key(id_string),
			self.redis_table.get_friend_table_user_id_field()
			)

	def get_online_player_list(self, redis):
		return redis.get(self.redis_table.get_online_player_list_key())

	def get_level_rank(self, redis, member_string):
		return redis.zrank(self.redis_table.get_level_rank_key(), member_string)

	def get_race_score_rank(self, redis, id_string, member_string):
		return redis.zrank(self.redis_table.get_race_score_rank_key(id_string), member_string)

