#This file is generated by program. DO NOT EDIT IT MANUALLY!
class ClientProtocolID:
	#cgame id_start:0x1001
	#cauth id_start:0x0001
	P_AUTH_USER = 0x1
	R_AUTH_USER_SUCCESS = 0x10001
	R_AUTH_USER_FAILURE = 0x10002
	R_AUTH_USER_USER_NAME_INVALID = 0x10003
	#cgateway id_start:0x0101
