# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='client_message.proto',
  package='',
  serialized_pb='\n\x14\x63lient_message.proto\"-\n\x0b\x41uthUserReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\x0b\x41uthUserRes\x12\x0e\n\x06result\x18\x01 \x01(\x05')




_AUTHUSERREQ = descriptor.Descriptor(
  name='AuthUserReq',
  full_name='AuthUserReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='AuthUserReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='AuthUserReq.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=69,
)


_AUTHUSERRES = descriptor.Descriptor(
  name='AuthUserRes',
  full_name='AuthUserRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='AuthUserRes.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=71,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['AuthUserReq'] = _AUTHUSERREQ
DESCRIPTOR.message_types_by_name['AuthUserRes'] = _AUTHUSERRES

class AuthUserReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHUSERREQ
  
  # @@protoc_insertion_point(class_scope:AuthUserReq)

class AuthUserRes(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHUSERRES
  
  # @@protoc_insertion_point(class_scope:AuthUserRes)

# @@protoc_insertion_point(module_scope)
